# permissions for end users to view wikis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wiki-viewer-role
rules:
- apiGroups:
  - batch.wiki.kubebuilder.io
  resources:
  - wikis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.wiki.kubebuilder.io
  resources:
  - wikis/status
  verbs:
  - get
