# permissions for end users to edit wikis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wiki-editor-role
rules:
- apiGroups:
  - batch.wiki.kubebuilder.io
  resources:
  - wikis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.wiki.kubebuilder.io
  resources:
  - wikis/status
  verbs:
  - get
